### ISSUE TITLE
issues with elgg 2.1

### ISSUE THREAD

**Issue by propertunist** [mrclay/Elgg-mrclay_combiner#2]
i am testing this with elgg 2.1 here and notice the following:
- i replaced fontawesome 4.5 in my theme plugin's start.php file, with the 4.6.1 version of fontawesome by unregistering version 4.5 and then registering and loading 4.6.1. when i activate the combiner plugin, this change is lost and 4.5 is loaded.
- the long list of AMD modules that i inserted into the combiner plugin's admin area have not been combined into one file when i load a page.
- i do not see any reduction in the number of files loaded on the activity page on my site or a reduction in the page weight.

**Comment by mrclay** [comment]
Hmm, I see it doesn't flush the cache. Try that.

**Comment by mrclay** [comment]
I just committed the cache flush.

**Comment by propertunist** [comment]
thanks, though that hasn't resolved the issue. i can still see the individual files in the page source.
this is the content of the admin panel:

```
elgg/Plugin,
elgg/init,
elgg/ready,
elgg/spinner,
text,
elgg/reportedcontent,
ureka/shorten,
framework/categories/tree,
framework/categories/menu,
search_advanced/ajax_submit,
target_blank/target_blank,
filter_and_sort/sort_ui,
elgg_cookieconsent/cookieconsent,
elgg_cookieconsent/cookieconsent_init,
ureka/ureka
```

**Comment by mrclay** [comment]
> still see the individual files in the page source

But are they actually loaded via HTTP request? RequireJS might alter HTML for some reason. What matters is network activity.

**Comment by propertunist** [comment]
right ok, it looks like there are around 10 less file transfers when the plugin is activated, so it is working. i was thinking that maybe this plugin does more than it does, since i had just been looking at your minify plugin that would probably reduce the file size transfers too. SPDY essentially performs the role of this plugin doesn't it?
